pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Clone Repo') {
            steps {
                // Required for ALX checker
                sh 'git branch'
                git credentialsId: '24a6edd8-5863-4cdd-b2c9-e1b9a2ffe57c', url: 'https://github.com/Mariemtijani/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv $VENV'
                sh './$VENV/bin/pip3 install --upgrade pip'
                // Required for ALX checker
                sh './$VENV/bin/pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './$VENV/bin/pytest --maxfail=1 --disable-warnings -q > report.txt'
            }
        }

        stage('Archive Report') {
            steps {
                archiveArtifacts artifacts: 'report.txt', fingerprint: true
            }
        }
    }
}
